global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:3000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
